# Generated by Django 4.0.1 on 2022-02-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='Bőr',
            field=models.CharField(choices=[('1', 'Normál'), ('2', 'Meleg'), ('3', 'Hűvös'), ('4', 'Sápadt'), ('5', 'Sárga'), ('6', 'Cyanotikus'), ('7', 'Márványozott'), ('8', 'Kiütéses')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='Köhögés',
            field=models.CharField(choices=[('1', 'Nincs'), ('2', 'Száraz'), ('3', 'Produktív'), ('4', 'Köhécselő'), ('5', 'Rohamszerű'), ('6', 'Inger'), ('7', 'Ugató')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='Légzési munka',
            field=models.CharField(choices=[('1', 'Normál'), ('2', 'Fokozott'), ('3', 'Gyengülő')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='Pulzus',
            field=models.CharField(choices=[('1', 'Ritmusos'), ('2', 'Aritmiás')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='RR bo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='triage',
            name='SpO2',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
