# Generated by Django 4.0.1 on 2022-03-15 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('triage', '0002_remove_triage_beteg azonosító_remove_triage_lf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
