# Generated by Django 4.0.2 on 2022-03-02 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0004_triage_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='triage',
            name='triage_category',
            field=models.CharField(choices=[('1', '1 - Azonnali - P'), ('2', '2 - 15 perc - S'), ('3', '3 - 30 perc - Z'), ('4', '4 - 60 perc - K'), ('5', '5 - 120 perc - Sz')], default=1, max_length=1, verbose_name='Triage Kategória'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='triage',
            name='treatment',
            field=models.BooleanField(default=False, verbose_name='Kezelés alatt'),
        ),
    ]
